# .github/ISSUE_TEMPLATE/documentation.yml
name: 📘 Documentation
description: Improve or add documentation
title: "[DOCS] "
labels: ["documentation", "NSOC'26", "level1"]

body:
  - type: dropdown
    id: level
    attributes:
      label: Difficulty Level
      options:
        - level1 (easy)
        - level2 (medium)
        - level3 (hard)

  - type: textarea
    id: details
    attributes:
      label: What needs improvement?